apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyser
spec:
  selector:
    matchLabels:
      app: analyser
  replicas: 1
  template:
    metadata:
      labels:
        app: analyser
    spec:
      containers:
      - name: analyser
        image: yuragranovsky/pulse-monitoring_analyser
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: CLOUDKARAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: kafkaPassword
                name: monitoring-secret
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: redisPassword
                name: monitoring-secret             
        
---
apiVersion: v1
kind: Service
metadata:
  name: analyser
spec:
  selector:
    app: analyser
  type: ClusterIP
  ports:
  - port: 10000
    targetPort: 10000

