apiVersion: apps/v1
kind: Deployment
metadata:
  name: avg-values-populator
spec:
  selector:
    matchLabels:
      app: avg-values-populator
  replicas: 1
  template:
    metadata:
      labels:
        app: avg-values-populator
    spec:
      containers:
      - name: avg-values-populator
        image: yuragranovsky/pulse-monitoring_avg-values-populator
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: CLOUDKARAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: kafkaPassword
                name: monitoring-secret
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongoPassword
                name: monitoring-secret             
        
---
apiVersion: v1
kind: Service
metadata:
  name: avg-values-populator
spec:
  selector:
    app: avg-values-populator
  type: ClusterIP
  ports:
  - port: 10000
    targetPort: 10000

