apiVersion: apps/v1
kind: Deployment
metadata:
  name: avg-values-back-office
spec:
  selector:
    matchLabels:
      app: avg-values-back-office
  replicas: 1
  template:
    metadata:
      labels:
        app: avg-values-back-office
    spec:
      containers:
      - name: avg-values-back-office
        image: yuragranovsky/pulse-monitoring_avg-values-back-office
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongoPassword
                name: monitoring-secret
        ports:
        - containerPort: 8585
---
apiVersion: v1
kind: Service
metadata:
  name: avg-values-back-office
spec:
  selector:
    app: avg-values-back-office
  type: ClusterIP
  ports:
  - port: 8585
    targetPort: 8585

