apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-patient-data-provider
spec:
  selector:
    matchLabels:
      app: doctor-patient-data-provider
  replicas: 1
  template:
    metadata:
      labels:
        app: doctor-patient-data-provider
    spec:
      containers:
      - name: doctor-patient-data-provider
        image: yuragranovsky/pulse-monitoring_doctor-patient-data-provider
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresPassword
                name: monitoring-secret
        ports:
        - containerPort: 8282
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-patient-data-provider
spec:
  selector:
    app: doctor-patient-data-provider
  type: ClusterIP
  ports:
  - port: 8282
    targetPort: 8282

