apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumps-mail-notifier
spec:
  selector:
    matchLabels:
      app: jumps-mail-notifier
  replicas: 2
  template:
    metadata:
      labels:
        app: jumps-mail-notifier
    spec:
      containers:
      - name: jumps-mail-notifier
        image: yuragranovsky/pulse-monitoring_jumps-mail-notifier
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: DATA_PROVIDER_HOST
            valueFrom:
              configMapKeyRef:
                key: dataProviderHost
                name: monitoring-config-map
          - name: CLOUDKARAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: kafkaPassword
                name: monitoring-secret
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mailPassword
                name: monitoring-secret            
        
---
apiVersion: v1
kind: Service
metadata:
  name: jumps-mail-notifier
spec:
  selector:
    app: jumps-mail-notifier
  type: ClusterIP
  ports:
  - port: 10000
    targetPort: 10000

