apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: yuragranovsky/pulse-monitoring_monitoring-config-server
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
---  
apiVersion: v1
kind: Service
metadata:
  name: monitoring-config-server
spec:
  selector:
    app: config-server
  type: ClusterIP 
  ports:
  - port: 8888
    targetPort: 8888
      
