apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-gateway
spec:
  selector:
    matchLabels:
      app: security-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: security-gateway
    spec:
      containers:
      - name: security-gateway
        image: yuragranovsky/pulse-monitoring_security-gateway
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: security-gateway
spec:
  selector:
    app: security-gateway
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30000

