apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-back-office
spec:
  selector:
    matchLabels:
      app: visits-back-office
  replicas: 2
  template:
    metadata:
      labels:
        app: visits-back-office
    spec:
      containers:
      - name: visits-back-office
        image: yuragranovsky/pulse-monitoring_visits-back-office
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: springProfilesActive
                name: monitoring-config-map
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresPassword
                name: monitoring-secret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: visits-back-office
spec:
  selector:
    app: visits-back-office
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080

